### PR TITLE
refactor for classes and format (changed to mjs)

### PR DESCRIPTION
**Pull request by jd-apprentice**
- Changing from object to classes
- format: js -> mjs

### CODE REVIEW

**Comment by jd-apprentice** [comment]
```Error: Route.get() requires a callback function but got a [object Undefined]``` Si te podes chusmear esto genial (?) @ScorpionConMate

**Comment by jd-apprentice** [comment]
No se puede aceptar este PR por el siguiente error -> ```Error: Route.get() requires a callback function but got a [object Undefined]```

**Comment by jd-apprentice** [comment]
Posible solucion: https://stackoverflow.com/questions/36558909/route-get-requires-callback-functions-but-got-a-object-undefined

**Comment by ScorpionConMate** [comment]
Checkout this https://github.com/hifrontendcafe/Calobot/blob/main/src/server/routes/mentorship.routes.ts

**Pull request merged**
